spring:
  rsocket:
    server:
      port: 7000

playground:
  serviceUrl: https://httpbin.org
  auth:
    login: user
    password: user
  admin:
    login: admin
    password: admin
  guest:
    login: guest
    password: guest
